spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_review_bot
    username: postgres
    password:
  cloud:
    gcp:
      sql:
        database-name: messenger_review_bot
        enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    crypto:
      secret-key: connectly-secret-key
      salt: a3f8f1d44e22104e

connectly:
  messenger-platform:
    webhook:
      verify-token: connectly-coding-challenge
    send-api:
      base-url: https://graph.facebook.com
      version: v17.0
      review-question-id: 7b46c20a8c1e475f8f5f2f98408e2a75
      postback:
        persistent-menu-payload: PERSISTENT_MENU_REVIEW
        quick-replies-payload: QUICK_REPLIES_REVIEW
        get-started-payload: GET_STARTED_REVIEW
    messenger-profile-api:
      base-url: https://graph.facebook.com/v2.6/me
    meta-for-developers:
      app-id: 820451813151477

server:
  error:
    include-message: always
  port: 8080
